const actionNames = {
  LOADING_STARTED: "LOADING_STARTED",
  AUTH_ERROR: "AUTH_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
  SIGN_OUT: "SIGN_OUT",
  GET_PROFILES_SUCCEEDED: "GET_PROFILES_SUCCEEDED",
  GET_PROFILES_STARTED: "GET_PROFILES_STARTED",
  GET_PROFILES_FAILED: "GET_PROFILES_FAILED",
  SELECT_PROFILE: "SELECT_PROFILE",
  INITIAL_SELECT_PROFILE: "INITIAL_SELECT_PROFILE",
  SWITCH_USER: "SWITCH_USER",

  SET_ONBOARDING_STATUS: "SET_ONBOARDING_STATUS",
  AUTO_LOGIN: "AUTO_LOGIN",

  RESET_COMPLETED: "RESET_COMPLETED",
  RESET_CLEAR: "RESET_CLEAR",
};

export default actionNames;
