enum actionNames {
  LOADING_STARTED = 'LOADING_STARTED',
  ERROR = 'ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
  GET_STUDENT = 'GET_STUDENT',
  GET_CLASSROOM_CATEGORY = 'GET_CLASSROOM_CATEGORY',
  CLEAR_CLASSROOM_CATEGORY = 'CLEAR_CLASSROOM_CATEGORY',
  RECORD_ITEM_LOCAL = 'RECORD_ITEM_LOCAL',
  RECORD_ITEM_REMOTE = 'RECORD_ITEM_REMOTE',
  CLEAR_STATE = 'CLEAR_STATE',
  UPDATE_CLASSROOM_PROGRESS = 'UPDATE_CLASSROOM_PROGRESS',
  UPDATE_CLASSROOM_CATEGORY_PROGRESS = 'UPDATE_CLASSROOM_CATEGORY_PROGRESS',
}

export default actionNames;
