const actionNames = {
  LOADING_STARTED: "LOADING_STARTED",
  ERROR: "ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  GET_PROFILE_SUCCEEDED: "GET_PROFILE_SUCCEEDED",

  EDITING_PROFILE_SUCCEEDED: "EDIT_PROFILE_SUCCEEDED",
  EDITING_PROFILE_IMAGE: "EDIT_PROFILE_IMAGE",

  GET_STUDENT_CLASSROOM_CATEGORY: "GET_STUDENT_CLASSROOM_CATEGORY",
  CLEAR_STUDENT_CLASSROOM_CATEGORY: "CLEAR_STUDENT_CLASSROOM_CATEGORY",

  RATING_VOICE_SUCCEEDED: "RATING_VOICE_SUUCCEEDED",

  CREATE_STUDENT: "CREATE_STUDENT",

  EDITING_STUDENT_SUCCEEDED: "EDITING_STUDENT_SUCCEEDED",
  EDITING_STUDENT_IMAGE: "EDITING_STUDENT_IMAGE",
  DELETE_STUDENT_SUCCEEDED: "DELETE_STUDENT_SUCCEEDED",
  SAVING_STUDENT_STARTED: "SAVING_STUDENT_STARTED",
  SAVING_STUDENT_ERROR: "SAVING_STUDENT_ERROR",
  SAVING_STUDENT_CLEAR_ERROR: "SAVING_STUDENT_CLEAR_ERROR",

  GET_CATEGORY_PROGRESS: "GET_CATEGORY_PROGRESS",
  CLEAR_CATEGORY_PROGRESS: "CLEAR_CATEGORY_PROGRESS",
  RECORD_CATEGORY_ITEM_LOCAL: "RECORD_CATEGORY_ITEM_LOCAL",
  RECORD_CATEGORY_ITEM_REMOTE: "RECORD_CATEGORY_ITEM_REMOTE",

  EDITING_SET_SUCCEEDED: "EDITING_SET_SUCCEEDED",
  EDITING_SET_IMAGE: "EDITING_SET_IMAGE",
  DELETE_SET_SUCCEEDED: "DELETE_SET_SUCCEEDED",
  SAVING_SET_STARTED: "SAVING_SET_STARTED",
  SAVING_SET_ERROR: "SAVING_SET_ERROR",
  SAVING_SET_CLEAR_ERROR: "SAVING_SET_CLEAR_ERROR",
  ADDING_SET_ITEM: "ADDING_SET_ITEM",
  EDITING_SET_ITEM_IMAGE: "EDITING_SET_ITEM_IMAGE",
  DELETE_SET_ITEM_SUCCEEDED: "DELETE_SET_ITEM_SUCCEEDED",
  CREATE_SET: "CREATE_SET",

  TICKET_SUBMIT_SUCCEEDED: "TICKET_SUBMIT_SUCCEEDED",

  CLEAR_STATE: "CLEAR_STATE",

  CONFIRM_TUTORIAL: "CONFIRM_TUTORIAL",
};

export default actionNames;
